FROM nginx:alpine

# Install Node.js runtime
RUN apk add --update nodejs npm

# Copy Nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Set up Node.js app
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .

# set up node on the background and start nginx
CMD node index.js & nginx -g 'daemon off;'

EXPOSE 80